micronaut:
  application:
    name: member-management
  security:
    enabled: false
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
mongo:
  connection-string: mongodb://username:password@localhost:49153/library?authSource=admin&readPreference=primary&ssl=false
